server:
  port: 8081

spring:
  application:
    name: bqss
  datasource:
    druid:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.113.128:3306/study?characterEncoding=UTF-8
        username: root
        password: 123456
logging:
  config: classpath:logback-spring.xml

#这里不需要配置了，我们自定义了sqlSessionFactory
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
